### ISSUE TITLE
submodule cannot be cloned anymore

### ISSUE THREAD

**Issue by birkenfeld** [esrf-bliss/Lima-camera-slsdetector#2]
Since github has removed the `git://` protocol, the submodule should switch to using `https://`

**Comment by alejandrohomsp** [comment]
Thanks @birkenfeld for creating the issue. I have pushed the master and jungfrau branches with a fix. Could you please confirm that it's OK now?

**Comment by birkenfeld** [comment]
Yes, cloning works now, just needs an update in the main Lima repo. Thanks!

**Comment by alejandrohomsp** [comment]
I am waiting for a merge of jungfrau/eiger into the master branch of Lima-camera-slsdetector before updating the main Lima repository. Hope that it won't take too long ;)
